### ISSUE TITLE
error in hybridlambdaformat

### ISSUE THREAD

**Issue by crsl4** [crsl4/PhyloNetworks.jl#113]
Hello,

I tried to use the function `hybridlambdaformat` on the Cui network (h=5), and I get an error:

```
using PhyloNetworks, PhyloPlots
net = readTopology("(Xmayae,((Xhellerii,((((((((((((Xgordoni,Xmeyeri):0.263,Xcouchianus):3.532,Xvariatus):0.646,Xevelynae):0.411,(Xxiphidium,#H24:0.0::0.167):1.374):0.293,Xmilleri):0.47,Xandersi):0.65,Xmaculatus):1.022,((((Xmontezumae,(Xcortezi,((Xmalinche_CHIC2,Xbirchmanni_GARC):1.077)#H26:0.02::0.869):1.28):0.634,((Xnigrensis,(Xmultilineatus)#H27:::0.92):1.927,(#H27:::0.08,(Xcontinens,Xpygmaeus):1.113):0.888):2.344):1.104,#H26:7.247::0.131):1.248)#H24:0.302::0.833):0.758,(Xmonticolus,(Xclemenciae_F2)#H28:::0.92):1.949):1.15,#H28:::0.08):0.647)#H25:1.058::0.57):0.682,Xalvarezi):0.285,(Xsignum,#H25:9.773::0.43):4.897);")

hybridlambdaformat(net)
##ERROR: did not find Hname# twice for some one (or more) of the hybrid names
```

However, if I `plot(net)`, I don't see any issue with the number of hybrid nodes, so I don't understand where this error is coming from.

Thanks!
Claudia

**Comment by cecileane** [comment]
That's because one of the taxon names contains an "H" (Xmalinche_CHIC2), and is written someone close to a hybrid node. Let me see if I can make a quick fix.

**Comment by cecileane** [comment]
should be fixed with 893a65a5

**Comment by crsl4** [comment]
Thanks! I am unable to get the new changes, even after updating. I am still in commit 33ad39ac. I am tracking the master branch.

```
(v1.2) pkg> update
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Updating git-repo `https://github.com/crsl4/PhyloNetworks.jl.git`
 Resolving package versions...
  Updating `~/.julia/environments/v1.2/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.2/Manifest.toml`
 [no changes]

(v1.2) pkg> status
    Status `~/.julia/environments/v1.2/Project.toml`
  [33ad39ac] PhyloNetworks v0.11.0 #master (https://github.com/crsl4/PhyloNetworks.jl.git)
  [c0d5b6db] PhyloPlots v0.2.1
```

**Comment by cecileane** [comment]
`[33ad39ac]` is the identifier of the package, not the commit SHA.

**Comment by crsl4** [comment]
Thanks Cecile! I figured it out and I do have the correction in my files, but I still have the error. I am actually reading the network from a file. If I copy the text from the file:
```
net = readTopology("(Xmayae,((Xhellerii,((((((((((((Xgordoni,Xmeyeri):0.26288003539447563,Xcouchianus):3.5316206217653274,Xvariatus):0.6455291326119673,Xevelynae):0.4111685702431165,(Xxiphidium,#H24:5.24460669974415e-7::0.1668054423118095):1.3741742525902727):0.2929829215332769,Xmilleri):0.4699283116965078,Xandersi):0.6495881117323812,Xmaculatus):1.0219292263416704,((((Xmontezumae,(Xcortezi,((Xmalinche_CHIC2,Xbirchmanni_GARC):1.076581051819183)#H26:0.020332521129393374::0.869412679921953):1.2795080898457403):0.6342192691008461,((Xnigrensis,(Xmultilineatus)#H27:::0.9196276851750825):1.9267265788980392,(#H27:::0.0803723148249175,(Xcontinens,Xpygmaeus):1.1133638730620816):0.8879852120835154):2.343672147813728):1.103951991906288,#H26:7.246926015211305::0.13058732007804696):1.2481251155312258)#H24:0.3023656122436739::0.8331945576881905):0.757785564757215,(Xmonticolus,(Xclemenciae_F2)#H28:::0.9198459069223606):1.949276643450234):1.149729004325246,#H28:::0.08015409307763947):0.6473757665476981)#H25:1.0581245012020082::0.569624299891438):0.6822757414084448,Xalvarezi):0.28538412154183945,(Xsignum,#H25:9.772583434987848::0.4303757001085619):4.897252902886207);")
hybridlambdaformat(net)
```

**Comment by cecileane** [comment]
ah... now it's the scientific notation for numbers, with `5.24460669974415e-7`

**Comment by cecileane** [comment]
Commit https://github.com/crsl4/PhyloNetworks.jl/commit/3b83ad78fbc7eac11eeba8246f7f1f2091c60bcc should fix the issue, which occurred with branch lengths (or gamma) in e notation. Can you try again?

**Comment by crsl4** [comment]
Perfect! No more error, thanks Cecile!
